import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import ReduxProvider from "@/providers/ReduxProvider";

const roboto = {
  style: {
    fontFamily: 'Roboto, Helvetica, Arial, sans-serif',
  },
};



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />

        {children}
        <Footer />
        </ReduxProvider>
        

      </body>
    </html>
  );
}
